name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: "16.17.0"
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null
      - run: ng build --output-path docs --base-href /data-structures/
