name: End-to-end tests
on: [push]
jobs:
  deploy-run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
        with:
            node-version: 16.17.0
    - name: npm dependencies
      run: npm install
    - name: Build
      run: npm run build -- --prod
    - name: Checkout
    - run: npm run build-deploy
